language: java
install: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Pproduction
deploy:
  provider: releases
  api_key:
    secure: jRY9FzaK5ThU9hsey9rpMH3E3SHZIIK1W2IRZjmjagMTCTACL7tN7JbdKqGR6zVuhCBTlLVsbEOa7tatW/eIwCfduQAAu4kxfrP5RGH1sOyWj0wCIhiu1sVVeSJAzdb8Qek6ambzEGG39XSqdoAXQKIh5XDyebw9TDbEWV5dqx0dHsrXZERagMFay0ShOUYYUINo8nuOD7VlF+Tc26jmDTJ85BDNsklMcel/s6PjAAD406XCKdHhJhGU6p7g/p4y8z1djUR+SS7Hu18phv1hWsZy6D+9G9UU7a1itLOpfzwvSozYvqxj/JmZjeGBElGof4vRYlwh1wifEQiqtS5HF3eRK8JEwdWE0ArEwp+wlgHiFUsw4PBP5GsuismM0Hero/lhTChKYWfmiW1aQ1INIC2vSuSTpjqitW44/0UcPwzkgpcGES2TZcmqE/kB9vByzUYPdGW9RcIy9S3biPpnOdw32D+Bcpc2kRLIa/MR4074nlP8OY7yQMpTKsle1s1Urq1HDeBdsVnN2TF+4VtM0myJ4VibRqaZXGu8UO1b3UDCrGj4iYHGyqF9FOwN2G0kSaRcyfQzx7ME82NnYU07ohAUhorsSS6wifzy1HsoSXSDJJQQV5Ud17waeWZQrjMq+Sy10WwVBgtexf9FMHfKdj0NS6oqScjgZU0nGHzkZ5g=
  file: acrarium/target/acrarium-*.war
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
