name: release-docker

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '1.13'
      - name: Build release
        run: ./mvnw -B clean package -Pproduction
      - name: Build image
        run: ./mvnw -B dockerfile:build -Pproduction -pl acrarium
      - name: Publish to hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: f43nd1r/acrarium
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
