name: release-docker

on:
  push:
    tags:
      - 'v*'

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '1.13'
      - name: Build release
        run: ./mvnw -B clean package -Pproduction -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version
        id: version
        run: echo ::set-output name=value::$(./mvnw org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep '^[0-9]')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to hub (latest)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: f43nd1r/acrarium:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: acrarium
      - name: Publish to hub (version tag)
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: f43nd1r/acrarium:${{ steps.version.outputs.value }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: acrarium