name: tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '1.11', '1.14' ]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Maven tests on Java ${{ matrix.java }}
      run: ./mvnw -B clean test
