name: tests

on: [push]

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '15' ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: tests on Java ${{ matrix.java }}
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: jdk${{ matrix.java }}
          arguments: test
          properties: org.gradle.jvmargs="-Dvaadin.proKey=${{ secrets.VAADIN_PROKEY }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
